INSERT INTO "phrases" VALUES (1, '¡Hola!', 'Hello',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "phrases" VALUES (2, 'Bienvenidos a 272', 'Welcome to 272',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "phrases" VALUES (1, 'Buenos dias', 'Good morning',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "phrases" VALUES (2, '¿Que onda?', 'What is up?',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "phrases" VALUES (1, 'Desde luego', 'Of course',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "phrases" VALUES (2, 'Que padre', 'How cool',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "phrases" VALUES (1, 'Tienes coco', 'You are smart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO "phrases" VALUES (2, '¿Neta?', 'For real?',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);